"""
dependencies.py

Attribute dependencies of a generated MapLibre style.

Field pruning must be driven by what each *source layer's* style layers
actually read — never by searching for a field name in ``str(style)``, which
keeps fields whose name happens to occur anywhere (and keeps them for every
layer) and silently deletes fields referenced in a different spelling.
"""

import re
from typing import Dict, Iterable, Set

from .expressions import referenced_fields

_TOKEN_RE = re.compile(r"\{([^{}]+)\}")

# Attributes that must survive pruning regardless of style references
# (feature identity for popups/interaction and rule description).
ALWAYS_KEEP = frozenset({"q2vt_orig_id", "q2vt_description"})


def layer_field_dependencies(layer: dict) -> Set[str]:
    fields: Set[str] = set()
    if "filter" in layer:
        fields |= referenced_fields(layer["filter"])
    for section in ("layout", "paint"):
        for key, value in (layer.get(section) or {}).items():
            fields |= referenced_fields(value)
            if key == "text-field" and isinstance(value, str):
                fields |= set(_TOKEN_RE.findall(value))
    return fields


def style_field_dependencies(style: dict) -> Dict[str, Set[str]]:
    """``{source_layer: {field, ...}}`` for every vector style layer."""
    deps: Dict[str, Set[str]] = {}
    for layer in style.get("layers", []):
        source_layer = layer.get("source-layer")
        if not source_layer:
            continue
        deps.setdefault(source_layer, set()).update(layer_field_dependencies(layer))
    return deps


def merge_dependencies(*maps: Dict[str, Iterable[str]]) -> Dict[str, Set[str]]:
    merged: Dict[str, Set[str]] = {}
    for mapping in maps:
        for key, values in (mapping or {}).items():
            merged.setdefault(key, set()).update(values)
    return merged


def prunable_fields(existing: Iterable[str], required: Iterable[str],
                    prefix: str = "q2vt_property_") -> Set[str]:
    """Generated property fields that no consumer reads.

    Only fields generated by the exporter (``prefix``) are ever pruned; user
    attributes are controlled by the "Included Fields" option instead.
    """
    required_set = set(required) | ALWAYS_KEEP
    return {name for name in existing if name.startswith(prefix) and name not in required_set}
